name: Build Docker image

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 3 * * *' # Daily at 03:00

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Build the Docker image and publish to registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: d0si/vortex
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: Dockerfile
        tags: "latest"
        cache: ${{ github.event_name != 'schedule' }}
